name: Execute test cases 
on:
  workflow_dispatch:
run-name: Execute test cases 
jobs:
  EXECUTE TESTS:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        environment: [dev, prod]
    services:
      app:
        image: ghcr.io/danielsilva-loanpro/sdet-interview-challenge:latest
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Execute Schedule Test Suite
        run: npm run ${{ matrix.environment }}

      - name: Upload html report
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: ${{ matrix.environment }}-Execution-Report
          path: playwright-report/
          retention-days: 1